#!/usr/bin/env python3
"""Generate PSrc/Chart.p from src/osd/PeeringState.h, and check the model.

The PeeringState statechart (boost::statechart) is taken from the header:
every state, its outer state, its initial inner state, and its reaction
list in order. An event is looked up in a state's list by exact type; a
`boost::statechart::event_base` entry matches any event (Initial, Reset and
Started end their lists with `transition<event_base, Crashed>`). A
custom_reaction whose event has no react() overload of its own resolves to
the state's `react(const event_base&)`, which discards.

usage:
  chartgen.py gen      <ceph src/osd> <out Chart.p>
  chartgen.py dispatch <ceph src/osd> <Pg.p>
  chartgen.py check    <ceph src/osd> <model .p files...>
dispatch rewrites the generated region of Pg.p: Custom() calls
R_<State>_<Event> for each custom reaction; Enter() and Exit() call each
state's En_<State> and Ex_<State> (its constructor and exit()).
The check fails unless the model defines a function R_<State>_<Event> for
every custom reaction, and none that is not one.
"""
import re, sys, os

def parse(osd):
    hdr = open(os.path.join(osd, 'PeeringState.h')).read()
    evh = open(os.path.join(osd, 'PGPeeringEvent.h')).read()
    src = open(os.path.join(osd, 'PeeringState.cc')).read()

    events = []
    for text in (evh, hdr):
        for m in re.finditer(r'TrivialEvent\((\w+)\)|struct (\w+)\s*:\s*boost::statechart::event<\s*\w+\s*>', text):
            name = m.group(1) or m.group(2)
            if name != 'T' and name not in events:
                events.append(name)

    states = {}
    order = []
    for m in re.finditer(r'struct (\w+)\s*:\s*boost::statechart::state<\s*(\w+)\s*,\s*(\w+)\s*(?:,\s*(\w+)\s*)?>', hdr):
        name, _, parent, initial = m.groups()
        # the struct body runs to the next struct declaring a state (or the end)
        nxt = re.search(r'\n  struct \w+\s*:\s*boost::statechart::state<', hdr[m.end():])
        body = hdr[m.end(): m.end() + nxt.start()] if nxt else hdr[m.end():]
        lst = re.search(r'boost::mpl::list\s*<(.*?)>\s*reactions;', body, re.S)
        reactions = []
        if lst:
            for r in re.finditer(r'boost::statechart::(custom_reaction|transition|deferral)\s*<\s*([\w:]+)\s*(?:,\s*(\w+)\s*)?>', lst.group(1)):
                kind, ev, tgt = r.groups()
                ev = 'event_base' if ev.endswith('event_base') else ev
                reactions.append([kind, ev, tgt])
        declared = set(re.findall(r'result\s+react\s*\(\s*const\s+([\w:]+)\s*&', body))
        declared = {('event_base' if d.endswith('event_base') else d) for d in declared}
        for r in reactions:
            if r[0] == 'custom_reaction':
                if r[1] in declared:
                    r[2] = 'custom'
                elif 'event_base' in declared:
                    r[2] = 'discard'          # resolves to react(const event_base&)
                else:
                    raise SystemExit(f'{name}: custom_reaction<{r[1]}> has no react()')
            elif r[0] == 'deferral':
                raise SystemExit(f'{name}: deferral<{r[1]}> is not supported')
        states[name] = dict(parent=parent, initial=initial, reactions=reactions)
        order.append(name)
    for s in states.values():
        for k, ev, _ in s['reactions']:
            if ev != 'event_base' and ev not in events:
                events.append(ev)
    return states, order, events

def path(states, s):
    p = []
    while s in states:
        p.insert(0, s)
        s = states[s]['parent']
    return '/'.join(p)

def gen(osd, out):
    states, order, events = parse(osd)
    L = []
    w = L.append
    w('// Generated by chartgen.py from src/osd/PeeringState.h and PGPeeringEvent.h.')
    w('// Do not edit; run ./chartgen.py gen ../../../../osd PSrc/Chart.p')
    w('')
    w('enum tS { S_NONE, ' + ', '.join('S_' + s for s in order) + ' }')
    w('')
    w('enum tE {')
    for i in range(0, len(events), 6):
        w('  ' + ', '.join('E_' + e for e in events[i:i + 6]) + (',' if i + 6 < len(events) else ''))
    w('}')
    w('')
    w('// RK_CUSTOM: the state\'s own react(); RK_DISCARD: its react(const event_base&)')
    w('enum tRk { RK_NONE, RK_CUSTOM, RK_DISCARD, RK_TRANSITION }')
    w('type tReaction = (kind: tRk, target: tS);')
    w('')
    w('fun Parent(s: tS): tS {')
    for s in order:
        p = states[s]['parent']
        if p in states:
            w(f'  if (s == S_{s}) {{ return S_{p}; }}')
    w('  return S_NONE;')
    w('}')
    w('')
    w('fun InitialOf(s: tS): tS {')
    for s in order:
        if states[s]['initial']:
            w(f'  if (s == S_{s}) {{ return S_{states[s]["initial"]}; }}')
    w('  return S_NONE;')
    w('}')
    w('')
    w('fun EventName(e: tE): string {')
    for e in events:
        w(f'  if (e == E_{e}) {{ return "{e}"; }}')
    w('  return "?";')
    w('}')
    w('')
    w('fun StateName(s: tS): string {')
    for s in order:
        w(f'  if (s == S_{s}) {{ return "{path(states, s)}"; }}')
    w('  return "none";')
    w('}')
    w('')
    w('// the first entry of s\'s reaction list that matches e')
    w('fun Reaction(s: tS, e: tE): tReaction {')
    for s in order:
        rs = states[s]['reactions']
        if not rs:
            continue
        w(f'  if (s == S_{s}) {{')
        for k, ev, tgt in rs:
            if k == 'custom_reaction':
                kind = 'RK_CUSTOM' if tgt == 'custom' else 'RK_DISCARD'
                res = f'(kind = {kind}, target = S_NONE)'
            else:
                res = f'(kind = RK_TRANSITION, target = S_{tgt})'
            if ev == 'event_base':
                w(f'    return {res};')
            else:
                w(f'    if (e == E_{ev}) {{ return {res}; }}')
        w('  }')
    w('  return (kind = RK_NONE, target = S_NONE);')
    w('}')
    w('')
    open(out, 'w').write('\n'.join(L))
    ncustom = sum(1 for s in states.values() for r in s['reactions'] if r[2] == 'custom')
    print(f'{len(states)} states, {len(events)} events, '
          f'{sum(len(s["reactions"]) for s in states.values())} reactions ({ncustom} custom) -> {out}')

def check(osd, files):
    states, order, events = parse(osd)
    want = {f'R_{s}_{r[1]}' for s in order for r in states[s]['reactions'] if r[2] == 'custom'}
    text = '\n'.join(open(f).read() for f in files)
    have = set(re.findall(r'fun (R_\w+)\s*\(', text))
    missing, extra = sorted(want - have), sorted(have - want)
    for m in missing:
        print('missing', m)
    for x in extra:
        print('not a custom reaction', x)
    print(f'{len(want & have)}/{len(want)} custom reactions implemented')
    return 1 if missing or extra else 0

BEGIN = '  // BEGIN GENERATED DISPATCH\n'
END = '  // END GENERATED DISPATCH\n'

def dispatch(osd, pg):
    states, order, events = parse(osd)
    L = [BEGIN]
    w = lambda x='': L.append(x + '\n')
    w('  // generated by chartgen.py dispatch; do not edit')
    w('  fun Custom(s: tS, ev: tEvt): tResult {')
    for st in order:
        cs = [r[1] for r in states[st]['reactions'] if r[2] == 'custom']
        if not cs:
            continue
        w(f'    if (s == S_{st}) {{')
        for ev in cs:
            w(f'      if (ev.e == E_{ev}) {{ return R_{st}_{ev}(ev); }}')
        w('    }')
    w('    assert false, format("osd.{0}: no react() for {1} in {2}", me, ev.e, StateName(s));')
    w('    return RES_DISCARD;')
    w('  }')
    w()
    for fn, pre in (('Enter', 'En'), ('Exit', 'Ex')):
        w(f'  fun {fn}(s: tS) {{')
        for st in order:
            w(f'    if (s == S_{st}) {{ {pre}_{st}(); return; }}')
        w('  }')
        w()
    L.append(END)
    text = open(pg).read()
    a, b = text.index(BEGIN), text.index(END) + len(END)
    open(pg, 'w').write(text[:a] + ''.join(L) + text[b:])
    print(f'{len(order)} states -> {pg}')

if __name__ == '__main__':
    if sys.argv[1] == 'gen':
        gen(sys.argv[2], sys.argv[3])
    elif sys.argv[1] == 'dispatch':
        dispatch(sys.argv[2], sys.argv[3])
    else:
        sys.exit(check(sys.argv[2], sys.argv[3:]))
