// Generated by chartgen.py from src/osd/PeeringState.h and PGPeeringEvent.h.
// Do not edit; run ./chartgen.py gen ../../../../osd PSrc/Chart.p

enum tS { S_NONE, S_Crashed, S_Initial, S_Reset, S_Started, S_Start, S_Primary, S_WaitActingChange, S_Peering, S_Active, S_Clean, S_Recovered, S_Backfilling, S_WaitRemoteBackfillReserved, S_WaitLocalBackfillReserved, S_NotBackfilling, S_NotRecovering, S_ReplicaActive, S_RepRecovering, S_RepWaitBackfillReserved, S_RepWaitRecoveryReserved, S_RepNotRecovering, S_Recovering, S_WaitRemoteRecoveryReserved, S_WaitLocalRecoveryReserved, S_Activating, S_Stray, S_ToDelete, S_WaitDeleteReserved, S_Deleting, S_GetInfo, S_GetLog, S_GetMissing, S_WaitUpThru, S_Down, S_Incomplete }

enum tE {
  E_MInfoRec, E_MLogRec, E_MNotifyRec, E_MQuery, E_MTrim, E_MLease,
  E_MLeaseAck, E_RequestBackfillPrio, E_RequestRecoveryPrio, E_NullEvt, E_PgCreateEvt, E_RemoteBackfillReserved,
  E_RemoteReservationRejectedTooFull, E_RemoteReservationRevokedTooFull, E_RemoteReservationRevoked, E_RemoteReservationCanceled, E_RemoteRecoveryReserved, E_RecoveryDone,
  E_DeferRecovery, E_DeferBackfill, E_RenewLease, E_QueryState, E_QueryUnfound, E_AdvMap,
  E_ActMap, E_Activate, E_ActivateCommitted, E_UnfoundBackfill, E_UnfoundRecovery, E_RequestScrub,
  E_Initialize, E_GotInfo, E_NeedUpThru, E_Backfilled, E_LocalBackfillReserved, E_RejectTooFullRemoteReservation,
  E_RequestBackfill, E_RemoteRecoveryPreempted, E_RemoteBackfillPreempted, E_BackfillTooFull, E_RecoveryTooFull, E_MakePrimary,
  E_MakeStray, E_NeedActingChange, E_IsIncomplete, E_RepeatGetLog, E_IsDown, E_AllReplicasRecovered,
  E_DoRecovery, E_LocalRecoveryReserved, E_AllRemotesReserved, E_AllBackfillsReserved, E_GoClean, E_AllReplicasActivated,
  E_IntervalFlush, E_DeleteStart, E_DeleteSome, E_SetForceRecovery, E_UnsetForceRecovery, E_SetForceBackfill,
  E_UnsetForceBackfill, E_DeleteReserved, E_DeleteInterrupted, E_CheckReadable, E_GotLog
}

// RK_CUSTOM: the state's own react(); RK_DISCARD: its react(const event_base&)
enum tRk { RK_NONE, RK_CUSTOM, RK_DISCARD, RK_TRANSITION }
type tReaction = (kind: tRk, target: tS);

fun Parent(s: tS): tS {
  if (s == S_Start) { return S_Started; }
  if (s == S_Primary) { return S_Started; }
  if (s == S_WaitActingChange) { return S_Primary; }
  if (s == S_Peering) { return S_Primary; }
  if (s == S_Active) { return S_Primary; }
  if (s == S_Clean) { return S_Active; }
  if (s == S_Recovered) { return S_Active; }
  if (s == S_Backfilling) { return S_Active; }
  if (s == S_WaitRemoteBackfillReserved) { return S_Active; }
  if (s == S_WaitLocalBackfillReserved) { return S_Active; }
  if (s == S_NotBackfilling) { return S_Active; }
  if (s == S_NotRecovering) { return S_Active; }
  if (s == S_ReplicaActive) { return S_Started; }
  if (s == S_RepRecovering) { return S_ReplicaActive; }
  if (s == S_RepWaitBackfillReserved) { return S_ReplicaActive; }
  if (s == S_RepWaitRecoveryReserved) { return S_ReplicaActive; }
  if (s == S_RepNotRecovering) { return S_ReplicaActive; }
  if (s == S_Recovering) { return S_Active; }
  if (s == S_WaitRemoteRecoveryReserved) { return S_Active; }
  if (s == S_WaitLocalRecoveryReserved) { return S_Active; }
  if (s == S_Activating) { return S_Active; }
  if (s == S_Stray) { return S_Started; }
  if (s == S_ToDelete) { return S_Started; }
  if (s == S_WaitDeleteReserved) { return S_ToDelete; }
  if (s == S_Deleting) { return S_ToDelete; }
  if (s == S_GetInfo) { return S_Peering; }
  if (s == S_GetLog) { return S_Peering; }
  if (s == S_GetMissing) { return S_Peering; }
  if (s == S_WaitUpThru) { return S_Peering; }
  if (s == S_Down) { return S_Peering; }
  if (s == S_Incomplete) { return S_Peering; }
  return S_NONE;
}

fun InitialOf(s: tS): tS {
  if (s == S_Started) { return S_Start; }
  if (s == S_Primary) { return S_Peering; }
  if (s == S_Peering) { return S_GetInfo; }
  if (s == S_Active) { return S_Activating; }
  if (s == S_ReplicaActive) { return S_RepNotRecovering; }
  if (s == S_ToDelete) { return S_WaitDeleteReserved; }
  return S_NONE;
}

fun EventName(e: tE): string {
  if (e == E_MInfoRec) { return "MInfoRec"; }
  if (e == E_MLogRec) { return "MLogRec"; }
  if (e == E_MNotifyRec) { return "MNotifyRec"; }
  if (e == E_MQuery) { return "MQuery"; }
  if (e == E_MTrim) { return "MTrim"; }
  if (e == E_MLease) { return "MLease"; }
  if (e == E_MLeaseAck) { return "MLeaseAck"; }
  if (e == E_RequestBackfillPrio) { return "RequestBackfillPrio"; }
  if (e == E_RequestRecoveryPrio) { return "RequestRecoveryPrio"; }
  if (e == E_NullEvt) { return "NullEvt"; }
  if (e == E_PgCreateEvt) { return "PgCreateEvt"; }
  if (e == E_RemoteBackfillReserved) { return "RemoteBackfillReserved"; }
  if (e == E_RemoteReservationRejectedTooFull) { return "RemoteReservationRejectedTooFull"; }
  if (e == E_RemoteReservationRevokedTooFull) { return "RemoteReservationRevokedTooFull"; }
  if (e == E_RemoteReservationRevoked) { return "RemoteReservationRevoked"; }
  if (e == E_RemoteReservationCanceled) { return "RemoteReservationCanceled"; }
  if (e == E_RemoteRecoveryReserved) { return "RemoteRecoveryReserved"; }
  if (e == E_RecoveryDone) { return "RecoveryDone"; }
  if (e == E_DeferRecovery) { return "DeferRecovery"; }
  if (e == E_DeferBackfill) { return "DeferBackfill"; }
  if (e == E_RenewLease) { return "RenewLease"; }
  if (e == E_QueryState) { return "QueryState"; }
  if (e == E_QueryUnfound) { return "QueryUnfound"; }
  if (e == E_AdvMap) { return "AdvMap"; }
  if (e == E_ActMap) { return "ActMap"; }
  if (e == E_Activate) { return "Activate"; }
  if (e == E_ActivateCommitted) { return "ActivateCommitted"; }
  if (e == E_UnfoundBackfill) { return "UnfoundBackfill"; }
  if (e == E_UnfoundRecovery) { return "UnfoundRecovery"; }
  if (e == E_RequestScrub) { return "RequestScrub"; }
  if (e == E_Initialize) { return "Initialize"; }
  if (e == E_GotInfo) { return "GotInfo"; }
  if (e == E_NeedUpThru) { return "NeedUpThru"; }
  if (e == E_Backfilled) { return "Backfilled"; }
  if (e == E_LocalBackfillReserved) { return "LocalBackfillReserved"; }
  if (e == E_RejectTooFullRemoteReservation) { return "RejectTooFullRemoteReservation"; }
  if (e == E_RequestBackfill) { return "RequestBackfill"; }
  if (e == E_RemoteRecoveryPreempted) { return "RemoteRecoveryPreempted"; }
  if (e == E_RemoteBackfillPreempted) { return "RemoteBackfillPreempted"; }
  if (e == E_BackfillTooFull) { return "BackfillTooFull"; }
  if (e == E_RecoveryTooFull) { return "RecoveryTooFull"; }
  if (e == E_MakePrimary) { return "MakePrimary"; }
  if (e == E_MakeStray) { return "MakeStray"; }
  if (e == E_NeedActingChange) { return "NeedActingChange"; }
  if (e == E_IsIncomplete) { return "IsIncomplete"; }
  if (e == E_RepeatGetLog) { return "RepeatGetLog"; }
  if (e == E_IsDown) { return "IsDown"; }
  if (e == E_AllReplicasRecovered) { return "AllReplicasRecovered"; }
  if (e == E_DoRecovery) { return "DoRecovery"; }
  if (e == E_LocalRecoveryReserved) { return "LocalRecoveryReserved"; }
  if (e == E_AllRemotesReserved) { return "AllRemotesReserved"; }
  if (e == E_AllBackfillsReserved) { return "AllBackfillsReserved"; }
  if (e == E_GoClean) { return "GoClean"; }
  if (e == E_AllReplicasActivated) { return "AllReplicasActivated"; }
  if (e == E_IntervalFlush) { return "IntervalFlush"; }
  if (e == E_DeleteStart) { return "DeleteStart"; }
  if (e == E_DeleteSome) { return "DeleteSome"; }
  if (e == E_SetForceRecovery) { return "SetForceRecovery"; }
  if (e == E_UnsetForceRecovery) { return "UnsetForceRecovery"; }
  if (e == E_SetForceBackfill) { return "SetForceBackfill"; }
  if (e == E_UnsetForceBackfill) { return "UnsetForceBackfill"; }
  if (e == E_DeleteReserved) { return "DeleteReserved"; }
  if (e == E_DeleteInterrupted) { return "DeleteInterrupted"; }
  if (e == E_CheckReadable) { return "CheckReadable"; }
  if (e == E_GotLog) { return "GotLog"; }
  return "?";
}

fun StateName(s: tS): string {
  if (s == S_Crashed) { return "Crashed"; }
  if (s == S_Initial) { return "Initial"; }
  if (s == S_Reset) { return "Reset"; }
  if (s == S_Started) { return "Started"; }
  if (s == S_Start) { return "Started/Start"; }
  if (s == S_Primary) { return "Started/Primary"; }
  if (s == S_WaitActingChange) { return "Started/Primary/WaitActingChange"; }
  if (s == S_Peering) { return "Started/Primary/Peering"; }
  if (s == S_Active) { return "Started/Primary/Active"; }
  if (s == S_Clean) { return "Started/Primary/Active/Clean"; }
  if (s == S_Recovered) { return "Started/Primary/Active/Recovered"; }
  if (s == S_Backfilling) { return "Started/Primary/Active/Backfilling"; }
  if (s == S_WaitRemoteBackfillReserved) { return "Started/Primary/Active/WaitRemoteBackfillReserved"; }
  if (s == S_WaitLocalBackfillReserved) { return "Started/Primary/Active/WaitLocalBackfillReserved"; }
  if (s == S_NotBackfilling) { return "Started/Primary/Active/NotBackfilling"; }
  if (s == S_NotRecovering) { return "Started/Primary/Active/NotRecovering"; }
  if (s == S_ReplicaActive) { return "Started/ReplicaActive"; }
  if (s == S_RepRecovering) { return "Started/ReplicaActive/RepRecovering"; }
  if (s == S_RepWaitBackfillReserved) { return "Started/ReplicaActive/RepWaitBackfillReserved"; }
  if (s == S_RepWaitRecoveryReserved) { return "Started/ReplicaActive/RepWaitRecoveryReserved"; }
  if (s == S_RepNotRecovering) { return "Started/ReplicaActive/RepNotRecovering"; }
  if (s == S_Recovering) { return "Started/Primary/Active/Recovering"; }
  if (s == S_WaitRemoteRecoveryReserved) { return "Started/Primary/Active/WaitRemoteRecoveryReserved"; }
  if (s == S_WaitLocalRecoveryReserved) { return "Started/Primary/Active/WaitLocalRecoveryReserved"; }
  if (s == S_Activating) { return "Started/Primary/Active/Activating"; }
  if (s == S_Stray) { return "Started/Stray"; }
  if (s == S_ToDelete) { return "Started/ToDelete"; }
  if (s == S_WaitDeleteReserved) { return "Started/ToDelete/WaitDeleteReserved"; }
  if (s == S_Deleting) { return "Started/ToDelete/Deleting"; }
  if (s == S_GetInfo) { return "Started/Primary/Peering/GetInfo"; }
  if (s == S_GetLog) { return "Started/Primary/Peering/GetLog"; }
  if (s == S_GetMissing) { return "Started/Primary/Peering/GetMissing"; }
  if (s == S_WaitUpThru) { return "Started/Primary/Peering/WaitUpThru"; }
  if (s == S_Down) { return "Started/Primary/Peering/Down"; }
  if (s == S_Incomplete) { return "Started/Primary/Peering/Incomplete"; }
  return "none";
}

// the first entry of s's reaction list that matches e
fun Reaction(s: tS, e: tE): tReaction {
  if (s == S_Initial) {
    if (e == E_Initialize) { return (kind = RK_TRANSITION, target = S_Reset); }
    if (e == E_NullEvt) { return (kind = RK_DISCARD, target = S_NONE); }
    if (e == E_PgCreateEvt) { return (kind = RK_DISCARD, target = S_NONE); }
    return (kind = RK_TRANSITION, target = S_Crashed);
  }
  if (s == S_Reset) {
    if (e == E_QueryState) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_QueryUnfound) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_AdvMap) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_ActMap) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_NullEvt) { return (kind = RK_DISCARD, target = S_NONE); }
    if (e == E_PgCreateEvt) { return (kind = RK_DISCARD, target = S_NONE); }
    if (e == E_IntervalFlush) { return (kind = RK_CUSTOM, target = S_NONE); }
    return (kind = RK_TRANSITION, target = S_Crashed);
  }
  if (s == S_Started) {
    if (e == E_QueryState) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_QueryUnfound) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_AdvMap) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_IntervalFlush) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_NullEvt) { return (kind = RK_DISCARD, target = S_NONE); }
    if (e == E_PgCreateEvt) { return (kind = RK_DISCARD, target = S_NONE); }
    if (e == E_SetForceRecovery) { return (kind = RK_DISCARD, target = S_NONE); }
    if (e == E_UnsetForceRecovery) { return (kind = RK_DISCARD, target = S_NONE); }
    if (e == E_SetForceBackfill) { return (kind = RK_DISCARD, target = S_NONE); }
    if (e == E_UnsetForceBackfill) { return (kind = RK_DISCARD, target = S_NONE); }
    if (e == E_RequestScrub) { return (kind = RK_DISCARD, target = S_NONE); }
    if (e == E_CheckReadable) { return (kind = RK_DISCARD, target = S_NONE); }
    return (kind = RK_TRANSITION, target = S_Crashed);
  }
  if (s == S_Start) {
    if (e == E_MakePrimary) { return (kind = RK_TRANSITION, target = S_Primary); }
    if (e == E_MakeStray) { return (kind = RK_TRANSITION, target = S_Stray); }
  }
  if (s == S_Primary) {
    if (e == E_ActMap) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_MNotifyRec) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_SetForceRecovery) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_UnsetForceRecovery) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_SetForceBackfill) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_UnsetForceBackfill) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_RequestScrub) { return (kind = RK_CUSTOM, target = S_NONE); }
  }
  if (s == S_WaitActingChange) {
    if (e == E_QueryState) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_QueryUnfound) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_AdvMap) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_MLogRec) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_MInfoRec) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_MNotifyRec) { return (kind = RK_CUSTOM, target = S_NONE); }
  }
  if (s == S_Peering) {
    if (e == E_QueryState) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_QueryUnfound) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_Activate) { return (kind = RK_TRANSITION, target = S_Active); }
    if (e == E_AdvMap) { return (kind = RK_CUSTOM, target = S_NONE); }
  }
  if (s == S_Active) {
    if (e == E_QueryState) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_QueryUnfound) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_ActMap) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_AdvMap) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_MInfoRec) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_MNotifyRec) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_MLogRec) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_MTrim) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_Backfilled) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_ActivateCommitted) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_AllReplicasActivated) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_DeferRecovery) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_DeferBackfill) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_UnfoundRecovery) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_UnfoundBackfill) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_RemoteReservationRevokedTooFull) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_RemoteReservationRevoked) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_DoRecovery) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_RenewLease) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_MLeaseAck) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_CheckReadable) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_PgCreateEvt) { return (kind = RK_CUSTOM, target = S_NONE); }
  }
  if (s == S_Clean) {
    if (e == E_DoRecovery) { return (kind = RK_TRANSITION, target = S_WaitLocalRecoveryReserved); }
    if (e == E_SetForceRecovery) { return (kind = RK_DISCARD, target = S_NONE); }
    if (e == E_SetForceBackfill) { return (kind = RK_DISCARD, target = S_NONE); }
  }
  if (s == S_Recovered) {
    if (e == E_GoClean) { return (kind = RK_TRANSITION, target = S_Clean); }
    if (e == E_DoRecovery) { return (kind = RK_TRANSITION, target = S_WaitLocalRecoveryReserved); }
    if (e == E_AllReplicasActivated) { return (kind = RK_CUSTOM, target = S_NONE); }
  }
  if (s == S_Backfilling) {
    if (e == E_Backfilled) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_DeferBackfill) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_UnfoundBackfill) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_RemoteReservationRejectedTooFull) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_RemoteReservationRevokedTooFull) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_RemoteReservationRevoked) { return (kind = RK_CUSTOM, target = S_NONE); }
  }
  if (s == S_WaitRemoteBackfillReserved) {
    if (e == E_RemoteBackfillReserved) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_RemoteReservationRejectedTooFull) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_RemoteReservationRevoked) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_AllBackfillsReserved) { return (kind = RK_TRANSITION, target = S_Backfilling); }
  }
  if (s == S_WaitLocalBackfillReserved) {
    if (e == E_LocalBackfillReserved) { return (kind = RK_TRANSITION, target = S_WaitRemoteBackfillReserved); }
    if (e == E_RemoteBackfillReserved) { return (kind = RK_CUSTOM, target = S_NONE); }
  }
  if (s == S_NotBackfilling) {
    if (e == E_QueryUnfound) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_RequestBackfill) { return (kind = RK_TRANSITION, target = S_WaitLocalBackfillReserved); }
    if (e == E_RemoteBackfillReserved) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_RemoteReservationRejectedTooFull) { return (kind = RK_CUSTOM, target = S_NONE); }
  }
  if (s == S_NotRecovering) {
    if (e == E_QueryUnfound) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_DoRecovery) { return (kind = RK_TRANSITION, target = S_WaitLocalRecoveryReserved); }
    if (e == E_DeferRecovery) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_UnfoundRecovery) { return (kind = RK_CUSTOM, target = S_NONE); }
  }
  if (s == S_ReplicaActive) {
    if (e == E_QueryState) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_QueryUnfound) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_ActMap) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_MQuery) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_MInfoRec) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_MLogRec) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_MTrim) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_Activate) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_ActivateCommitted) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_DeferRecovery) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_DeferBackfill) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_UnfoundRecovery) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_UnfoundBackfill) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_RemoteBackfillPreempted) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_RemoteRecoveryPreempted) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_RecoveryDone) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_BackfillTooFull) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_DeleteStart) { return (kind = RK_TRANSITION, target = S_ToDelete); }
    if (e == E_MLease) { return (kind = RK_CUSTOM, target = S_NONE); }
  }
  if (s == S_RepRecovering) {
    if (e == E_RecoveryDone) { return (kind = RK_TRANSITION, target = S_RepNotRecovering); }
    if (e == E_RemoteReservationRejectedTooFull) { return (kind = RK_TRANSITION, target = S_RepNotRecovering); }
    if (e == E_RemoteReservationCanceled) { return (kind = RK_TRANSITION, target = S_RepNotRecovering); }
    if (e == E_BackfillTooFull) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_RemoteRecoveryPreempted) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_RemoteBackfillPreempted) { return (kind = RK_CUSTOM, target = S_NONE); }
  }
  if (s == S_RepWaitBackfillReserved) {
    if (e == E_BackfillTooFull) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_RemoteBackfillReserved) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_RejectTooFullRemoteReservation) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_RemoteReservationRejectedTooFull) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_RemoteReservationCanceled) { return (kind = RK_CUSTOM, target = S_NONE); }
  }
  if (s == S_RepWaitRecoveryReserved) {
    if (e == E_RemoteRecoveryReserved) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_RemoteReservationRejectedTooFull) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_RemoteReservationCanceled) { return (kind = RK_CUSTOM, target = S_NONE); }
  }
  if (s == S_RepNotRecovering) {
    if (e == E_RequestRecoveryPrio) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_RequestBackfillPrio) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_RejectTooFullRemoteReservation) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_RemoteReservationRejectedTooFull) { return (kind = RK_TRANSITION, target = S_RepNotRecovering); }
    if (e == E_RemoteReservationCanceled) { return (kind = RK_TRANSITION, target = S_RepNotRecovering); }
    if (e == E_RemoteRecoveryReserved) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_RemoteBackfillReserved) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_RecoveryDone) { return (kind = RK_TRANSITION, target = S_RepNotRecovering); }
  }
  if (s == S_Recovering) {
    if (e == E_AllReplicasRecovered) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_DeferRecovery) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_UnfoundRecovery) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_RequestBackfill) { return (kind = RK_CUSTOM, target = S_NONE); }
  }
  if (s == S_WaitRemoteRecoveryReserved) {
    if (e == E_RemoteRecoveryReserved) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_AllRemotesReserved) { return (kind = RK_TRANSITION, target = S_Recovering); }
  }
  if (s == S_WaitLocalRecoveryReserved) {
    if (e == E_LocalRecoveryReserved) { return (kind = RK_TRANSITION, target = S_WaitRemoteRecoveryReserved); }
    if (e == E_RecoveryTooFull) { return (kind = RK_CUSTOM, target = S_NONE); }
  }
  if (s == S_Activating) {
    if (e == E_AllReplicasRecovered) { return (kind = RK_TRANSITION, target = S_Recovered); }
    if (e == E_DoRecovery) { return (kind = RK_TRANSITION, target = S_WaitLocalRecoveryReserved); }
    if (e == E_RequestBackfill) { return (kind = RK_TRANSITION, target = S_WaitLocalBackfillReserved); }
  }
  if (s == S_Stray) {
    if (e == E_MQuery) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_MLogRec) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_MInfoRec) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_ActMap) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_RecoveryDone) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_DeleteStart) { return (kind = RK_TRANSITION, target = S_ToDelete); }
  }
  if (s == S_ToDelete) {
    if (e == E_ActMap) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_ActivateCommitted) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_DeleteSome) { return (kind = RK_CUSTOM, target = S_NONE); }
  }
  if (s == S_WaitDeleteReserved) {
    if (e == E_DeleteReserved) { return (kind = RK_TRANSITION, target = S_Deleting); }
  }
  if (s == S_Deleting) {
    if (e == E_DeleteSome) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_DeleteInterrupted) { return (kind = RK_TRANSITION, target = S_WaitDeleteReserved); }
  }
  if (s == S_GetInfo) {
    if (e == E_QueryState) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_QueryUnfound) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_GotInfo) { return (kind = RK_TRANSITION, target = S_GetLog); }
    if (e == E_MNotifyRec) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_IsDown) { return (kind = RK_TRANSITION, target = S_Down); }
  }
  if (s == S_GetLog) {
    if (e == E_QueryState) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_QueryUnfound) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_MLogRec) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_GotLog) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_AdvMap) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_NeedActingChange) { return (kind = RK_TRANSITION, target = S_WaitActingChange); }
    if (e == E_IsIncomplete) { return (kind = RK_TRANSITION, target = S_Incomplete); }
    if (e == E_RepeatGetLog) { return (kind = RK_TRANSITION, target = S_GetLog); }
  }
  if (s == S_GetMissing) {
    if (e == E_QueryState) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_QueryUnfound) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_MLogRec) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_NeedUpThru) { return (kind = RK_TRANSITION, target = S_WaitUpThru); }
  }
  if (s == S_WaitUpThru) {
    if (e == E_QueryState) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_QueryUnfound) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_ActMap) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_MLogRec) { return (kind = RK_CUSTOM, target = S_NONE); }
  }
  if (s == S_Down) {
    if (e == E_QueryState) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_QueryUnfound) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_MNotifyRec) { return (kind = RK_CUSTOM, target = S_NONE); }
  }
  if (s == S_Incomplete) {
    if (e == E_AdvMap) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_MNotifyRec) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_QueryUnfound) { return (kind = RK_CUSTOM, target = S_NONE); }
    if (e == E_QueryState) { return (kind = RK_CUSTOM, target = S_NONE); }
  }
  return (kind = RK_NONE, target = S_NONE);
}
